spring.application.name=SemanticSearchAppl
spring.datasource.url=jdbc:postgresql://api_db_wfog_user:aGayj2EGHO2CB3BAp9XZ0nQeLx3KT20Z@dpg-d3vjjtfdiees73f1q0rg-a.oregon-postgres.render.com/api_db_wfog;
spring.datasource.username=api_db_wfog_user
spring.datasource.password=aGayj2EGHO2CB3BAp9XZ0nQeLx3KT20Z
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibermate.sql.show=true