spring.datasource.url=jdbc:postgresql://dpg-d3vklrndiees73f2mklg-a.oregon-postgres.render.com:5432/api_db_3bhe
spring.datasource.username=api_db_3bhe_user
spring.datasource.password=0PRNutjb9OnBfBxRSo5DHcLbZb6hXIAK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true